apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ui-calculator-service
  name: ui-calculator-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5173
  selector:
    app: ui-calculator
  type: ClusterIP
status:
  loadBalancer: {}
