apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-calculator-clusterip
  name: api-calculator-clusterip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: calculator-api
  type: ClusterIP
status:
  loadBalancer: {}
