apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: calculator-api
  name: calculator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: calculator-api
    spec:
      imagePullSecrets:
      - name: pulldocker
      containers:
      - image: {{ print $.Values.API.Image ":"  $.Values.API.tag }}
        name: calculator-api
        resources: {}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-env
        - secretRef:
            name: api-secret
status: {}
