
ENV: dev
API:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/kong-api"
  tag: "dev-1e855ad"
  API_KEY: "TEST_DEV"
UI:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/kong-ui"
  tag: "dev-0.0.1"
