
ENV: dev
API:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/kong-api"
  tag: "dev-e9a4a88"
  API_KEY: "TEST_DEV"
UI:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/kong-ui"
  tag: "dev"
